### ISSUE TITLE
Border Settings dialog controls are hidden on high DPI displays

### ISSUE THREAD

**Issue by ascottvhz** [madskristensen/SolutionColors#17]
As you can see from the screenshot below, the Cancel and OK buttons get clipped on my UHD display (3072x1920) scaled at 200%.

![image](https://user-images.githubusercontent.com/12252268/187722866-c84b00b6-fd3e-49af-a3ad-133b5382cad1.png)

**Comment by madskristensen** [comment]
@mkornreder any idea on how to make this scale with variuos DPIs? Wanna take a stab at it?

**Comment by mkornreder** [comment]
Yes i can try that. I'm currently working on displaying branches in different colors.
As soon as I have that I'll take care of the dpi right away.
I hope that I'll be ready in the next few days.

**Comment by mkornreder** [comment]
Has probably done with the last pull request, because the solution is in there.

(Branches still in work...)

**Comment by madskristensen** [comment]
@mkornreder Thanks. I'm curious how you'll get the branch name. There is no API for it in VS AFAIK

**Comment by madskristensen** [comment]
Fixed with latest PR

**Comment by mkornreder** [comment]
I have an idea. If I read the HEAD file in the .git folder, I find the branch name there. The solution is usually always inside a folder with .git directory, so i can go up until I find the .git directory in case the solution is in a subfolder.

I'm currently trying to use color gradients so that the color of the master and the branch can be displayed in the borders of a branch. Depending on the setting in the options, you can adjust the behavior.
The color of the master can only be adjusted when the master is opened, the color for the branch only if you have opened the branch. All colors are saved with the name of the branch in color.txt.
Maybe a dialog for managing the branches in color.txt would also be useful here.

What do you think about this?

**Comment by madskristensen** [comment]
Interesting idea. I'm game for an experiment, for sure
