### ISSUE TITLE
Allow installation in VS2019

### ISSUE THREAD

**Issue by LoLo2207** [madskristensen/SolutionColors#6]
Thanks for the extension. I'd like to use it in my work machine, where we use VS2019.

I changed the .vsixmanifest and other files from 17.0 to 16.0 and I've been able to install it, but when opening VS, the extension crashes.

Can it be ported to VS2019 or it's dependant on VS2022?

**Comment by harrym-kemkrest** [comment]
My company is still using 2019, and I suspect there are quite a few 2019 users remaining.

**Comment by luatnt-work** [comment]
@LoLo2207 and @harrym-kemkrest , you can use this extension - https://marketplace.visualstudio.com/items?itemName=Wumpf.SolutionColor - for your VS2019 :)

The extension above works really well with VS2019, but it seems that its author does not have any plan to update it to support VS2022 so that's why I am here :)

**Comment by madskristensen** [comment]
This extension will not be receiving support for VS 2019. I recommend the same solution as @luatnt-work suggested above

**Comment by Baccanno** [comment]
Thanks for the link !
